# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FastVideoPlayer
email: hello@fastvideo.player
description:  Video helper for all streaming website. It create more preload buffers with your video. Tested and works with KissAnime, MasterAnime, Xmovies8, Gomovies, 123movies
baseurl: "/FastVideoPlayer" # the subpath of your site, e.g. /blog
url: "https://chrome.google.com/webstore/detail/cdddngajilmhkjmeccbnmaificedkhlg" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
